<template>
  <v-container>
    <v-card :loading="loading">
      <v-card-title>
        <h3>{{ t('client.list') }}</h3>
      </v-card-title>
      <v-divider/>
      <v-list v-model:opened="activeGroup" open-strategy="single">
        <v-list-item>
          <v-btn
              color="primary"
              @click="addClient"
              :prepend-icon="addClientButton.icon"
              block
              :disabled="hasUnsavedClient"
          >{{ addClientButton.title }}
          </v-btn>
        </v-list-item>
        <v-list-group
            v-for="client in clients.data"
            :key="client.id"
            :value="client.id"
            expand-icon="mdi-menu-open"

        >
          <template v-slot:activator={props}>

            <v-list-item
                v-bind="props"
                :title="client.name"
                prepend-icon="mdi-cloud"
            ></v-list-item>
          </template>


          <v-list-item
          >
            <ClientPanel :client="client"/>
          </v-list-item>
        </v-list-group>
      </v-list>
    </v-card>
  </v-container>
</template>

<script setup lang="ts">
import {useRequest} from "alova";
import {clientListGetter} from "../../core/api/client.ts";
import {computed, ref, watchEffect} from "vue";
import ClientPanel from "./ClientPanel.vue";
import {useI18n} from "vue-i18n";

const {t} = useI18n()
let activeGroup = ref([])

const {loading, data, error, onSuccess} = useRequest(() => clientListGetter(), {
  initialData: ref([]),
  immediate: true,
})

const clients = ref(data)

// Add a display id for each client
onSuccess(event => {
  for (let i = 0; i < clients.value.data.length; i++) {
    clients.value.data[i].new = false
  }
})

function addClient() {
  clients.value.data.push({
    name: t('client.newClient'),
    id: 'Will be generated by server',
    type: '',
    create_at: '',
    modify_at: '',
    detail: {
      client_id: '',
      tenant_id: '',
      end_point: '',
    },
    new: true
  })

  activeGroup.value = ['Will be generated by server']
}

let hasUnsavedClient = ref(false)

watchEffect(() => {
  if(clients.value.data === undefined) {
    return
  }else{
    for (let i = 0; i < clients.value.data.length; i++) {
      if (clients.value.data[i].new) {
        hasUnsavedClient.value = true
        return
      }
    }
    hasUnsavedClient.value = false
  }
})

let addClientButton = ref({})
watchEffect(() => {
  if (hasUnsavedClient.value) {
    addClientButton.value = {
      title: t('client.unsaved'),
      icon: 'mdi-content-save'
    }
  } else {
    addClientButton.value = {
      title: t('client.add'),
      icon: 'mdi-plus'
    }
  }
})

</script>

<style scoped>

</style>