<template>
  <v-container>
    <v-card :loading="loading">
      <v-card-title>
        <h3>{{ t('client.list') }}</h3>
      </v-card-title>
      <v-list>
        <v-list-item>
          <v-btn
              color="primary"
              @click="addClient"
              prepend-icon="mdi-plus"
              block
          >{{ t('client.add') }}
          </v-btn>
        </v-list-item>
        <v-list-group
            v-for="client in clients.data"
            :key="client.id"
            :value="client.id"
            expand-icon="mdi-menu-open"
        >
          <template v-slot:activator="{ props }">

            <v-list-item
                v-bind="props"
                :title="client.name"
                prepend-icon="mdi-cloud"
            ></v-list-item>
          </template>


          <v-list-item
          >
            <ClientPanel :client="client"/>
          </v-list-item>
        </v-list-group>
      </v-list>
    </v-card>
  </v-container>
</template>

<script setup lang="ts">
import {useRequest} from "alova";
import {clientListGetter} from "../../core/api/client.ts";
import {ref} from "vue";
import ClientPanel from "./ClientPanel.vue";
import {useI18n} from "vue-i18n";

const {t} = useI18n()

const {loading, data, error} = useRequest(() => clientListGetter(), {
  initialData: ref([]),
  immediate: true,
})

const clients = ref(data)

function addClient() {
  clients.value.data.push({
    name: t('client.newClient'),
    id: 'Will be generated by server',
    type: '',
    create_at: '',
    modify_at: '',
    detail:{
      client_id: '',
      tenant_id: '',
      end_point: '',
    },
    new: true
  })
}

function saveConfig(){
}

</script>

<style scoped>

</style>